import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { MapEditorContextProvider } from "~/contexts/MapContext";
import { TooltipProvider } from "~/components/ui/tooltip";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen w-screen overflow-hidden">
        <TRPCReactProvider>
          <MapEditorContextProvider>
            <TooltipProvider>{children}</TooltipProvider>
          </MapEditorContextProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
